---
new_page_extension: md
auto_deploy: true
admin_path: "./"
webhook_url: 
sections:
- type: directory
  path: ''
  label: post
  create: all
  match: content/
  new_doc_ext: md
- type: directory
  path: content/industry-background-check
  label: Industry background check
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: ''
public_path: ''
front_matter_path: ":filename"
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
